# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Default command
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  up:
    desc: Spin up all the containers
    cmds:
      - sudo docker-compose up -d
    silent: true
  
  down:
    desc: Stop and delete all the containers
    cmds:
      - sudo docker-compose down
    silent: true

  reup:
    desc: Restarts all containers
    cmds:
      - sudo docker-compose down
      - sudo docker-compose up -d
    silent: true

  fmt:
    desc: Format code Oddo addon Python code
    dir: ./addons/
    cmds:
      - python -m black .
    silent: true

  curl:
    desc: Make a POST request with test payload on the "localhost:8069/case_study/applicant/get" REST API endpoint
    cmds:
      - curl -XPOST http://localhost:8069/case_study/applicant/get -H "Content-Type: application/json" -d @test_payload.json
    silent: true
